<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Full ISO 639-1 language catalog for vendor translation pairs.
     * Arabic and English stay first; remaining languages follow alphabetically (EN).
     *
     * @return list<array{code: string, native_name: string, direction: string, name_en: string, name_ar: string}>
     */
    protected function languages(): array
    {
        return [
            // Priority languages for UAE / Tarjuman
            ['code' => 'ar', 'native_name' => 'العربية', 'direction' => 'rtl', 'name_en' => 'Arabic', 'name_ar' => 'العربية'],
            ['code' => 'en', 'native_name' => 'English', 'direction' => 'ltr', 'name_en' => 'English', 'name_ar' => 'الإنجليزية'],

            // Full ISO 639-1 set (alphabetical by English name)
            ['code' => 'ab', 'native_name' => 'Аҧсуа', 'direction' => 'ltr', 'name_en' => 'Abkhazian', 'name_ar' => 'الأبخازية'],
            ['code' => 'aa', 'native_name' => 'Afaraf', 'direction' => 'ltr', 'name_en' => 'Afar', 'name_ar' => 'العفارية'],
            ['code' => 'af', 'native_name' => 'Afrikaans', 'direction' => 'ltr', 'name_en' => 'Afrikaans', 'name_ar' => 'الأفريقانية'],
            ['code' => 'ak', 'native_name' => 'Akan', 'direction' => 'ltr', 'name_en' => 'Akan', 'name_ar' => 'الأكانية'],
            ['code' => 'sq', 'native_name' => 'Shqip', 'direction' => 'ltr', 'name_en' => 'Albanian', 'name_ar' => 'الألبانية'],
            ['code' => 'am', 'native_name' => 'አማርኛ', 'direction' => 'ltr', 'name_en' => 'Amharic', 'name_ar' => 'الأمهرية'],
            ['code' => 'an', 'native_name' => 'Aragonés', 'direction' => 'ltr', 'name_en' => 'Aragonese', 'name_ar' => 'الأراغونية'],
            ['code' => 'hy', 'native_name' => 'Հայերեն', 'direction' => 'ltr', 'name_en' => 'Armenian', 'name_ar' => 'الأرمينية'],
            ['code' => 'as', 'native_name' => 'অসমীয়া', 'direction' => 'ltr', 'name_en' => 'Assamese', 'name_ar' => 'الأسامية'],
            ['code' => 'av', 'native_name' => 'Авар', 'direction' => 'ltr', 'name_en' => 'Avaric', 'name_ar' => 'الآوارية'],
            ['code' => 'ae', 'native_name' => 'Avesta', 'direction' => 'ltr', 'name_en' => 'Avestan', 'name_ar' => 'الأفستية'],
            ['code' => 'ay', 'native_name' => 'Aymar aru', 'direction' => 'ltr', 'name_en' => 'Aymara', 'name_ar' => 'الأيمارا'],
            ['code' => 'az', 'native_name' => 'Azərbaycan', 'direction' => 'ltr', 'name_en' => 'Azerbaijani', 'name_ar' => 'الأذربيجانية'],
            ['code' => 'bm', 'native_name' => 'Bamanankan', 'direction' => 'ltr', 'name_en' => 'Bambara', 'name_ar' => 'البامبارا'],
            ['code' => 'ba', 'native_name' => 'Башҡорт', 'direction' => 'ltr', 'name_en' => 'Bashkir', 'name_ar' => 'الباشكيرية'],
            ['code' => 'eu', 'native_name' => 'Euskara', 'direction' => 'ltr', 'name_en' => 'Basque', 'name_ar' => 'الباسكية'],
            ['code' => 'be', 'native_name' => 'Беларуская', 'direction' => 'ltr', 'name_en' => 'Belarusian', 'name_ar' => 'البيلاروسية'],
            ['code' => 'bn', 'native_name' => 'বাংলা', 'direction' => 'ltr', 'name_en' => 'Bengali', 'name_ar' => 'البنغالية'],
            ['code' => 'bi', 'native_name' => 'Bislama', 'direction' => 'ltr', 'name_en' => 'Bislama', 'name_ar' => 'البيسلاما'],
            ['code' => 'bs', 'native_name' => 'Bosanski', 'direction' => 'ltr', 'name_en' => 'Bosnian', 'name_ar' => 'البوسنية'],
            ['code' => 'br', 'native_name' => 'Brezhoneg', 'direction' => 'ltr', 'name_en' => 'Breton', 'name_ar' => 'البريتونية'],
            ['code' => 'bg', 'native_name' => 'Български', 'direction' => 'ltr', 'name_en' => 'Bulgarian', 'name_ar' => 'البلغارية'],
            ['code' => 'my', 'native_name' => 'မြန်မာဘာသာ', 'direction' => 'ltr', 'name_en' => 'Burmese', 'name_ar' => 'البورمية'],
            ['code' => 'ca', 'native_name' => 'Català', 'direction' => 'ltr', 'name_en' => 'Catalan', 'name_ar' => 'الكتالانية'],
            ['code' => 'ch', 'native_name' => 'Chamoru', 'direction' => 'ltr', 'name_en' => 'Chamorro', 'name_ar' => 'التشامورو'],
            ['code' => 'ce', 'native_name' => 'Нохчийн', 'direction' => 'ltr', 'name_en' => 'Chechen', 'name_ar' => 'الشيشانية'],
            ['code' => 'ny', 'native_name' => 'Chichewa', 'direction' => 'ltr', 'name_en' => 'Chichewa', 'name_ar' => 'التشيتشوا'],
            ['code' => 'zh', 'native_name' => '中文', 'direction' => 'ltr', 'name_en' => 'Chinese', 'name_ar' => 'الصينية'],
            ['code' => 'cu', 'native_name' => 'Ѩзыкъ словѣньскъ', 'direction' => 'ltr', 'name_en' => 'Church Slavic', 'name_ar' => 'السلافونية الكنسية'],
            ['code' => 'cv', 'native_name' => 'Чӑваш', 'direction' => 'ltr', 'name_en' => 'Chuvash', 'name_ar' => 'التشوفاشية'],
            ['code' => 'kw', 'native_name' => 'Kernewek', 'direction' => 'ltr', 'name_en' => 'Cornish', 'name_ar' => 'الكورنية'],
            ['code' => 'co', 'native_name' => 'Corsu', 'direction' => 'ltr', 'name_en' => 'Corsican', 'name_ar' => 'الكورسيكية'],
            ['code' => 'cr', 'native_name' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'direction' => 'ltr', 'name_en' => 'Cree', 'name_ar' => 'الكري'],
            ['code' => 'hr', 'native_name' => 'Hrvatski', 'direction' => 'ltr', 'name_en' => 'Croatian', 'name_ar' => 'الكرواتية'],
            ['code' => 'cs', 'native_name' => 'Čeština', 'direction' => 'ltr', 'name_en' => 'Czech', 'name_ar' => 'التشيكية'],
            ['code' => 'da', 'native_name' => 'Dansk', 'direction' => 'ltr', 'name_en' => 'Danish', 'name_ar' => 'الدانماركية'],
            ['code' => 'dv', 'native_name' => 'ދިވެހި', 'direction' => 'rtl', 'name_en' => 'Divehi', 'name_ar' => 'الديفهية'],
            ['code' => 'nl', 'native_name' => 'Nederlands', 'direction' => 'ltr', 'name_en' => 'Dutch', 'name_ar' => 'الهولندية'],
            ['code' => 'dz', 'native_name' => 'རྫོང་ཁ', 'direction' => 'ltr', 'name_en' => 'Dzongkha', 'name_ar' => 'الدزونخية'],
            ['code' => 'eo', 'native_name' => 'Esperanto', 'direction' => 'ltr', 'name_en' => 'Esperanto', 'name_ar' => 'الإسبرانتو'],
            ['code' => 'et', 'native_name' => 'Eesti', 'direction' => 'ltr', 'name_en' => 'Estonian', 'name_ar' => 'الإستونية'],
            ['code' => 'ee', 'native_name' => 'Eʋegbe', 'direction' => 'ltr', 'name_en' => 'Ewe', 'name_ar' => 'الإيوي'],
            ['code' => 'fo', 'native_name' => 'Føroyskt', 'direction' => 'ltr', 'name_en' => 'Faroese', 'name_ar' => 'الفاروية'],
            ['code' => 'fj', 'native_name' => 'Vosa Vakaviti', 'direction' => 'ltr', 'name_en' => 'Fijian', 'name_ar' => 'الفيجية'],
            ['code' => 'fi', 'native_name' => 'Suomi', 'direction' => 'ltr', 'name_en' => 'Finnish', 'name_ar' => 'الفنلندية'],
            ['code' => 'fr', 'native_name' => 'Français', 'direction' => 'ltr', 'name_en' => 'French', 'name_ar' => 'الفرنسية'],
            ['code' => 'ff', 'native_name' => 'Fulfulde', 'direction' => 'ltr', 'name_en' => 'Fulah', 'name_ar' => 'الفولانية'],
            ['code' => 'gl', 'native_name' => 'Galego', 'direction' => 'ltr', 'name_en' => 'Galician', 'name_ar' => 'الجاليكية'],
            ['code' => 'lg', 'native_name' => 'Luganda', 'direction' => 'ltr', 'name_en' => 'Ganda', 'name_ar' => 'اللوغندية'],
            ['code' => 'ka', 'native_name' => 'ქართული', 'direction' => 'ltr', 'name_en' => 'Georgian', 'name_ar' => 'الجورجية'],
            ['code' => 'de', 'native_name' => 'Deutsch', 'direction' => 'ltr', 'name_en' => 'German', 'name_ar' => 'الألمانية'],
            ['code' => 'el', 'native_name' => 'Ελληνικά', 'direction' => 'ltr', 'name_en' => 'Greek', 'name_ar' => 'اليونانية'],
            ['code' => 'gn', 'native_name' => 'Avañeʼẽ', 'direction' => 'ltr', 'name_en' => 'Guarani', 'name_ar' => 'الغوارانية'],
            ['code' => 'gu', 'native_name' => 'ગુજરાતી', 'direction' => 'ltr', 'name_en' => 'Gujarati', 'name_ar' => 'الغوجاراتية'],
            ['code' => 'ht', 'native_name' => 'Kreyòl ayisyen', 'direction' => 'ltr', 'name_en' => 'Haitian Creole', 'name_ar' => 'الكريولية الهايتية'],
            ['code' => 'ha', 'native_name' => 'Hausa', 'direction' => 'ltr', 'name_en' => 'Hausa', 'name_ar' => 'الهوسا'],
            ['code' => 'he', 'native_name' => 'עברית', 'direction' => 'rtl', 'name_en' => 'Hebrew', 'name_ar' => 'العبرية'],
            ['code' => 'hz', 'native_name' => 'Otjiherero', 'direction' => 'ltr', 'name_en' => 'Herero', 'name_ar' => 'الهيريرو'],
            ['code' => 'hi', 'native_name' => 'हिन्दी', 'direction' => 'ltr', 'name_en' => 'Hindi', 'name_ar' => 'الهندية'],
            ['code' => 'ho', 'native_name' => 'Hiri Motu', 'direction' => 'ltr', 'name_en' => 'Hiri Motu', 'name_ar' => 'الهيري موتو'],
            ['code' => 'hu', 'native_name' => 'Magyar', 'direction' => 'ltr', 'name_en' => 'Hungarian', 'name_ar' => 'المجرية'],
            ['code' => 'is', 'native_name' => 'Íslenska', 'direction' => 'ltr', 'name_en' => 'Icelandic', 'name_ar' => 'الآيسلندية'],
            ['code' => 'io', 'native_name' => 'Ido', 'direction' => 'ltr', 'name_en' => 'Ido', 'name_ar' => 'الإيدو'],
            ['code' => 'ig', 'native_name' => 'Igbo', 'direction' => 'ltr', 'name_en' => 'Igbo', 'name_ar' => 'الإيغبو'],
            ['code' => 'id', 'native_name' => 'Bahasa Indonesia', 'direction' => 'ltr', 'name_en' => 'Indonesian', 'name_ar' => 'الإندونيسية'],
            ['code' => 'ia', 'native_name' => 'Interlingua', 'direction' => 'ltr', 'name_en' => 'Interlingua', 'name_ar' => 'الإنترلينغوا'],
            ['code' => 'ie', 'native_name' => 'Interlingue', 'direction' => 'ltr', 'name_en' => 'Interlingue', 'name_ar' => 'الإنترلينغوي'],
            ['code' => 'iu', 'native_name' => 'ᐃᓄᒃᑎᑐᑦ', 'direction' => 'ltr', 'name_en' => 'Inuktitut', 'name_ar' => 'الإينكتيتوت'],
            ['code' => 'ik', 'native_name' => 'Iñupiaq', 'direction' => 'ltr', 'name_en' => 'Inupiaq', 'name_ar' => 'الإينوبياك'],
            ['code' => 'ga', 'native_name' => 'Gaeilge', 'direction' => 'ltr', 'name_en' => 'Irish', 'name_ar' => 'الأيرلندية'],
            ['code' => 'it', 'native_name' => 'Italiano', 'direction' => 'ltr', 'name_en' => 'Italian', 'name_ar' => 'الإيطالية'],
            ['code' => 'ja', 'native_name' => '日本語', 'direction' => 'ltr', 'name_en' => 'Japanese', 'name_ar' => 'اليابانية'],
            ['code' => 'jv', 'native_name' => 'Basa Jawa', 'direction' => 'ltr', 'name_en' => 'Javanese', 'name_ar' => 'الجاوية'],
            ['code' => 'kl', 'native_name' => 'Kalaallisut', 'direction' => 'ltr', 'name_en' => 'Kalaallisut', 'name_ar' => 'الكالاليست'],
            ['code' => 'kn', 'native_name' => 'ಕನ್ನಡ', 'direction' => 'ltr', 'name_en' => 'Kannada', 'name_ar' => 'الكانادا'],
            ['code' => 'kr', 'native_name' => 'Kanuri', 'direction' => 'ltr', 'name_en' => 'Kanuri', 'name_ar' => 'الكانوري'],
            ['code' => 'ks', 'native_name' => 'کٲشُر', 'direction' => 'rtl', 'name_en' => 'Kashmiri', 'name_ar' => 'الكشميرية'],
            ['code' => 'kk', 'native_name' => 'Қазақ', 'direction' => 'ltr', 'name_en' => 'Kazakh', 'name_ar' => 'الكازاخية'],
            ['code' => 'km', 'native_name' => 'ភាសាខ្មែរ', 'direction' => 'ltr', 'name_en' => 'Khmer', 'name_ar' => 'الخميرية'],
            ['code' => 'ki', 'native_name' => 'Gĩkũyũ', 'direction' => 'ltr', 'name_en' => 'Kikuyu', 'name_ar' => 'الكيكويو'],
            ['code' => 'rw', 'native_name' => 'Kinyarwanda', 'direction' => 'ltr', 'name_en' => 'Kinyarwanda', 'name_ar' => 'الكينيارواندا'],
            ['code' => 'ky', 'native_name' => 'Кыргызча', 'direction' => 'ltr', 'name_en' => 'Kirghiz', 'name_ar' => 'القيرغيزية'],
            ['code' => 'kv', 'native_name' => 'Коми', 'direction' => 'ltr', 'name_en' => 'Komi', 'name_ar' => 'الكومي'],
            ['code' => 'kg', 'native_name' => 'Kikongo', 'direction' => 'ltr', 'name_en' => 'Kongo', 'name_ar' => 'الكونغو'],
            ['code' => 'ko', 'native_name' => '한국어', 'direction' => 'ltr', 'name_en' => 'Korean', 'name_ar' => 'الكورية'],
            ['code' => 'kj', 'native_name' => 'Kuanyama', 'direction' => 'ltr', 'name_en' => 'Kuanyama', 'name_ar' => 'الكوانياما'],
            ['code' => 'ku', 'native_name' => 'Kurdî', 'direction' => 'ltr', 'name_en' => 'Kurdish', 'name_ar' => 'الكردية'],
            ['code' => 'lo', 'native_name' => 'ລາວ', 'direction' => 'ltr', 'name_en' => 'Lao', 'name_ar' => 'اللاوية'],
            ['code' => 'la', 'native_name' => 'Latina', 'direction' => 'ltr', 'name_en' => 'Latin', 'name_ar' => 'اللاتينية'],
            ['code' => 'lv', 'native_name' => 'Latviešu', 'direction' => 'ltr', 'name_en' => 'Latvian', 'name_ar' => 'اللاتفية'],
            ['code' => 'li', 'native_name' => 'Limburgs', 'direction' => 'ltr', 'name_en' => 'Limburgan', 'name_ar' => 'الليمبورغية'],
            ['code' => 'ln', 'native_name' => 'Lingála', 'direction' => 'ltr', 'name_en' => 'Lingala', 'name_ar' => 'اللينغالا'],
            ['code' => 'lt', 'native_name' => 'Lietuvių', 'direction' => 'ltr', 'name_en' => 'Lithuanian', 'name_ar' => 'الليتوانية'],
            ['code' => 'lu', 'native_name' => 'Tshiluba', 'direction' => 'ltr', 'name_en' => 'Luba-Katanga', 'name_ar' => 'اللوبا كاتانغا'],
            ['code' => 'lb', 'native_name' => 'Lëtzebuergesch', 'direction' => 'ltr', 'name_en' => 'Luxembourgish', 'name_ar' => 'اللوكسمبورغية'],
            ['code' => 'mk', 'native_name' => 'Македонски', 'direction' => 'ltr', 'name_en' => 'Macedonian', 'name_ar' => 'المقدونية'],
            ['code' => 'mg', 'native_name' => 'Malagasy', 'direction' => 'ltr', 'name_en' => 'Malagasy', 'name_ar' => 'الملغاشية'],
            ['code' => 'ms', 'native_name' => 'Bahasa Melayu', 'direction' => 'ltr', 'name_en' => 'Malay', 'name_ar' => 'الملايو'],
            ['code' => 'ml', 'native_name' => 'മലയാളം', 'direction' => 'ltr', 'name_en' => 'Malayalam', 'name_ar' => 'المالايالامية'],
            ['code' => 'mt', 'native_name' => 'Malti', 'direction' => 'ltr', 'name_en' => 'Maltese', 'name_ar' => 'المالطية'],
            ['code' => 'gv', 'native_name' => 'Gaelg', 'direction' => 'ltr', 'name_en' => 'Manx', 'name_ar' => 'المانكس'],
            ['code' => 'mi', 'native_name' => 'Māori', 'direction' => 'ltr', 'name_en' => 'Maori', 'name_ar' => 'الماورية'],
            ['code' => 'mr', 'native_name' => 'मराठी', 'direction' => 'ltr', 'name_en' => 'Marathi', 'name_ar' => 'الماراثية'],
            ['code' => 'mh', 'native_name' => 'Kajin M̧ajeļ', 'direction' => 'ltr', 'name_en' => 'Marshallese', 'name_ar' => 'المارشالية'],
            ['code' => 'mn', 'native_name' => 'Монгол', 'direction' => 'ltr', 'name_en' => 'Mongolian', 'name_ar' => 'المنغولية'],
            ['code' => 'na', 'native_name' => 'Dorerin Naoero', 'direction' => 'ltr', 'name_en' => 'Nauru', 'name_ar' => 'الناوروية'],
            ['code' => 'nv', 'native_name' => 'Diné bizaad', 'direction' => 'ltr', 'name_en' => 'Navajo', 'name_ar' => 'النافاجو'],
            ['code' => 'nd', 'native_name' => 'isiNdebele', 'direction' => 'ltr', 'name_en' => 'North Ndebele', 'name_ar' => 'النديبيلي الشمالية'],
            ['code' => 'nr', 'native_name' => 'isiNdebele', 'direction' => 'ltr', 'name_en' => 'South Ndebele', 'name_ar' => 'النديبيلي الجنوبية'],
            ['code' => 'ng', 'native_name' => 'Owambo', 'direction' => 'ltr', 'name_en' => 'Ndonga', 'name_ar' => 'الندونغا'],
            ['code' => 'ne', 'native_name' => 'नेपाली', 'direction' => 'ltr', 'name_en' => 'Nepali', 'name_ar' => 'النيبالية'],
            ['code' => 'se', 'native_name' => 'Davvisámegiella', 'direction' => 'ltr', 'name_en' => 'Northern Sami', 'name_ar' => 'السامي الشمالية'],
            ['code' => 'no', 'native_name' => 'Norsk', 'direction' => 'ltr', 'name_en' => 'Norwegian', 'name_ar' => 'النرويجية'],
            ['code' => 'nb', 'native_name' => 'Norsk bokmål', 'direction' => 'ltr', 'name_en' => 'Norwegian Bokmål', 'name_ar' => 'النرويجية بوكمال'],
            ['code' => 'nn', 'native_name' => 'Norsk nynorsk', 'direction' => 'ltr', 'name_en' => 'Norwegian Nynorsk', 'name_ar' => 'النرويجية نينوشك'],
            ['code' => 'oc', 'native_name' => 'Occitan', 'direction' => 'ltr', 'name_en' => 'Occitan', 'name_ar' => 'الأوكسيتانية'],
            ['code' => 'oj', 'native_name' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'direction' => 'ltr', 'name_en' => 'Ojibwa', 'name_ar' => 'الأوجيبوا'],
            ['code' => 'or', 'native_name' => 'ଓଡ଼ିଆ', 'direction' => 'ltr', 'name_en' => 'Odia', 'name_ar' => 'الأودية'],
            ['code' => 'om', 'native_name' => 'Afaan Oromoo', 'direction' => 'ltr', 'name_en' => 'Oromo', 'name_ar' => 'الأورومو'],
            ['code' => 'os', 'native_name' => 'Ирон', 'direction' => 'ltr', 'name_en' => 'Ossetian', 'name_ar' => 'الأوسيتية'],
            ['code' => 'pi', 'native_name' => 'पाऴि', 'direction' => 'ltr', 'name_en' => 'Pali', 'name_ar' => 'البالية'],
            ['code' => 'ps', 'native_name' => 'پښتو', 'direction' => 'rtl', 'name_en' => 'Pashto', 'name_ar' => 'البشتوية'],
            ['code' => 'fa', 'native_name' => 'فارسی', 'direction' => 'rtl', 'name_en' => 'Persian', 'name_ar' => 'الفارسية'],
            ['code' => 'pl', 'native_name' => 'Polski', 'direction' => 'ltr', 'name_en' => 'Polish', 'name_ar' => 'البولندية'],
            ['code' => 'pt', 'native_name' => 'Português', 'direction' => 'ltr', 'name_en' => 'Portuguese', 'name_ar' => 'البرتغالية'],
            ['code' => 'pa', 'native_name' => 'ਪੰਜਾਬੀ', 'direction' => 'ltr', 'name_en' => 'Punjabi', 'name_ar' => 'البنجابية'],
            ['code' => 'qu', 'native_name' => 'Runa Simi', 'direction' => 'ltr', 'name_en' => 'Quechua', 'name_ar' => 'الكيشوا'],
            ['code' => 'ro', 'native_name' => 'Română', 'direction' => 'ltr', 'name_en' => 'Romanian', 'name_ar' => 'الرومانية'],
            ['code' => 'rm', 'native_name' => 'Rumantsch', 'direction' => 'ltr', 'name_en' => 'Romansh', 'name_ar' => 'الرومانشية'],
            ['code' => 'rn', 'native_name' => 'Ikirundi', 'direction' => 'ltr', 'name_en' => 'Rundi', 'name_ar' => 'الروندية'],
            ['code' => 'ru', 'native_name' => 'Русский', 'direction' => 'ltr', 'name_en' => 'Russian', 'name_ar' => 'الروسية'],
            ['code' => 'sm', 'native_name' => 'Gagana faʻa Sāmoa', 'direction' => 'ltr', 'name_en' => 'Samoan', 'name_ar' => 'الساموية'],
            ['code' => 'sg', 'native_name' => 'Sängö', 'direction' => 'ltr', 'name_en' => 'Sango', 'name_ar' => 'السانغو'],
            ['code' => 'sa', 'native_name' => 'संस्कृतम्', 'direction' => 'ltr', 'name_en' => 'Sanskrit', 'name_ar' => 'السنسكريتية'],
            ['code' => 'sc', 'native_name' => 'Sardu', 'direction' => 'ltr', 'name_en' => 'Sardinian', 'name_ar' => 'السردينية'],
            ['code' => 'gd', 'native_name' => 'Gàidhlig', 'direction' => 'ltr', 'name_en' => 'Scottish Gaelic', 'name_ar' => 'الغيلية الاسكتلندية'],
            ['code' => 'sr', 'native_name' => 'Српски', 'direction' => 'ltr', 'name_en' => 'Serbian', 'name_ar' => 'الصربية'],
            ['code' => 'sn', 'native_name' => 'chiShona', 'direction' => 'ltr', 'name_en' => 'Shona', 'name_ar' => 'الشونا'],
            ['code' => 'ii', 'native_name' => 'ꆈꌠ꒿', 'direction' => 'ltr', 'name_en' => 'Sichuan Yi', 'name_ar' => 'اليي السيشوانية'],
            ['code' => 'sd', 'native_name' => 'سنڌي', 'direction' => 'rtl', 'name_en' => 'Sindhi', 'name_ar' => 'السندية'],
            ['code' => 'si', 'native_name' => 'සිංහල', 'direction' => 'ltr', 'name_en' => 'Sinhala', 'name_ar' => 'السنهالية'],
            ['code' => 'sk', 'native_name' => 'Slovenčina', 'direction' => 'ltr', 'name_en' => 'Slovak', 'name_ar' => 'السلوفاكية'],
            ['code' => 'sl', 'native_name' => 'Slovenščina', 'direction' => 'ltr', 'name_en' => 'Slovenian', 'name_ar' => 'السلوفينية'],
            ['code' => 'so', 'native_name' => 'Soomaali', 'direction' => 'ltr', 'name_en' => 'Somali', 'name_ar' => 'الصومالية'],
            ['code' => 'st', 'native_name' => 'Sesotho', 'direction' => 'ltr', 'name_en' => 'Southern Sotho', 'name_ar' => 'السوتو الجنوبية'],
            ['code' => 'es', 'native_name' => 'Español', 'direction' => 'ltr', 'name_en' => 'Spanish', 'name_ar' => 'الإسبانية'],
            ['code' => 'su', 'native_name' => 'Basa Sunda', 'direction' => 'ltr', 'name_en' => 'Sundanese', 'name_ar' => 'السوندانية'],
            ['code' => 'sw', 'native_name' => 'Kiswahili', 'direction' => 'ltr', 'name_en' => 'Swahili', 'name_ar' => 'السواحلية'],
            ['code' => 'ss', 'native_name' => 'SiSwati', 'direction' => 'ltr', 'name_en' => 'Swati', 'name_ar' => 'السواتي'],
            ['code' => 'sv', 'native_name' => 'Svenska', 'direction' => 'ltr', 'name_en' => 'Swedish', 'name_ar' => 'السويدية'],
            ['code' => 'tl', 'native_name' => 'Tagalog', 'direction' => 'ltr', 'name_en' => 'Tagalog', 'name_ar' => 'التاغالوغية'],
            ['code' => 'ty', 'native_name' => 'Reo Tahiti', 'direction' => 'ltr', 'name_en' => 'Tahitian', 'name_ar' => 'التاهيتية'],
            ['code' => 'tg', 'native_name' => 'Тоҷикӣ', 'direction' => 'ltr', 'name_en' => 'Tajik', 'name_ar' => 'الطاجيكية'],
            ['code' => 'ta', 'native_name' => 'தமிழ்', 'direction' => 'ltr', 'name_en' => 'Tamil', 'name_ar' => 'التاميلية'],
            ['code' => 'tt', 'native_name' => 'Татар', 'direction' => 'ltr', 'name_en' => 'Tatar', 'name_ar' => 'التتارية'],
            ['code' => 'te', 'native_name' => 'తెలుగు', 'direction' => 'ltr', 'name_en' => 'Telugu', 'name_ar' => 'التيلوغو'],
            ['code' => 'th', 'native_name' => 'ไทย', 'direction' => 'ltr', 'name_en' => 'Thai', 'name_ar' => 'التايلاندية'],
            ['code' => 'bo', 'native_name' => 'བོད་ཡིག', 'direction' => 'ltr', 'name_en' => 'Tibetan', 'name_ar' => 'التبتية'],
            ['code' => 'ti', 'native_name' => 'ትግርኛ', 'direction' => 'ltr', 'name_en' => 'Tigrinya', 'name_ar' => 'التيغرينية'],
            ['code' => 'to', 'native_name' => 'lea fakatonga', 'direction' => 'ltr', 'name_en' => 'Tonga', 'name_ar' => 'التونغية'],
            ['code' => 'ts', 'native_name' => 'Xitsonga', 'direction' => 'ltr', 'name_en' => 'Tsonga', 'name_ar' => 'التسونغا'],
            ['code' => 'tn', 'native_name' => 'Setswana', 'direction' => 'ltr', 'name_en' => 'Tswana', 'name_ar' => 'التسوانية'],
            ['code' => 'tr', 'native_name' => 'Türkçe', 'direction' => 'ltr', 'name_en' => 'Turkish', 'name_ar' => 'التركية'],
            ['code' => 'tk', 'native_name' => 'Türkmen', 'direction' => 'ltr', 'name_en' => 'Turkmen', 'name_ar' => 'التركمانية'],
            ['code' => 'tw', 'native_name' => 'Twi', 'direction' => 'ltr', 'name_en' => 'Twi', 'name_ar' => 'التوي'],
            ['code' => 'ug', 'native_name' => 'ئۇيغۇرچە', 'direction' => 'rtl', 'name_en' => 'Uighur', 'name_ar' => 'الأويغورية'],
            ['code' => 'uk', 'native_name' => 'Українська', 'direction' => 'ltr', 'name_en' => 'Ukrainian', 'name_ar' => 'الأوكرانية'],
            ['code' => 'ur', 'native_name' => 'اردو', 'direction' => 'rtl', 'name_en' => 'Urdu', 'name_ar' => 'الأردية'],
            ['code' => 'uz', 'native_name' => 'Oʻzbek', 'direction' => 'ltr', 'name_en' => 'Uzbek', 'name_ar' => 'الأوزبكية'],
            ['code' => 've', 'native_name' => 'Tshivenḓa', 'direction' => 'ltr', 'name_en' => 'Venda', 'name_ar' => 'الفيندا'],
            ['code' => 'vi', 'native_name' => 'Tiếng Việt', 'direction' => 'ltr', 'name_en' => 'Vietnamese', 'name_ar' => 'الفيتنامية'],
            ['code' => 'vo', 'native_name' => 'Volapük', 'direction' => 'ltr', 'name_en' => 'Volapük', 'name_ar' => 'الفولابوك'],
            ['code' => 'wa', 'native_name' => 'Walon', 'direction' => 'ltr', 'name_en' => 'Walloon', 'name_ar' => 'الوالونية'],
            ['code' => 'cy', 'native_name' => 'Cymraeg', 'direction' => 'ltr', 'name_en' => 'Welsh', 'name_ar' => 'الويلزية'],
            ['code' => 'fy', 'native_name' => 'Frysk', 'direction' => 'ltr', 'name_en' => 'Western Frisian', 'name_ar' => 'الفريزية الغربية'],
            ['code' => 'wo', 'native_name' => 'Wolof', 'direction' => 'ltr', 'name_en' => 'Wolof', 'name_ar' => 'الولوف'],
            ['code' => 'xh', 'native_name' => 'isiXhosa', 'direction' => 'ltr', 'name_en' => 'Xhosa', 'name_ar' => 'الخوسا'],
            ['code' => 'yi', 'native_name' => 'ייִדיש', 'direction' => 'rtl', 'name_en' => 'Yiddish', 'name_ar' => 'اليديشية'],
            ['code' => 'yo', 'native_name' => 'Yorùbá', 'direction' => 'ltr', 'name_en' => 'Yoruba', 'name_ar' => 'اليوروبا'],
            ['code' => 'za', 'native_name' => 'Saɯ cueŋƅ', 'direction' => 'ltr', 'name_en' => 'Zhuang', 'name_ar' => 'الزوانغ'],
            ['code' => 'zu', 'native_name' => 'isiZulu', 'direction' => 'ltr', 'name_en' => 'Zulu', 'name_ar' => 'الزولو'],

            // Extra regional variants useful for translation work
            ['code' => 'fil', 'native_name' => 'Filipino', 'direction' => 'ltr', 'name_en' => 'Filipino', 'name_ar' => 'الفلبينية'],
            ['code' => 'zh-cn', 'native_name' => '简体中文', 'direction' => 'ltr', 'name_en' => 'Chinese (Simplified)', 'name_ar' => 'الصينية المبسطة'],
            ['code' => 'zh-tw', 'native_name' => '繁體中文', 'direction' => 'ltr', 'name_en' => 'Chinese (Traditional)', 'name_ar' => 'الصينية التقليدية'],
            ['code' => 'pt-br', 'native_name' => 'Português (Brasil)', 'direction' => 'ltr', 'name_en' => 'Portuguese (Brazil)', 'name_ar' => 'البرتغالية (البرازيل)'],
            ['code' => 'pt-pt', 'native_name' => 'Português (Portugal)', 'direction' => 'ltr', 'name_en' => 'Portuguese (Portugal)', 'name_ar' => 'البرتغالية (البرتغال)'],
            ['code' => 'es-es', 'native_name' => 'Español (España)', 'direction' => 'ltr', 'name_en' => 'Spanish (Spain)', 'name_ar' => 'الإسبانية (إسبانيا)'],
            ['code' => 'es-mx', 'native_name' => 'Español (México)', 'direction' => 'ltr', 'name_en' => 'Spanish (Mexico)', 'name_ar' => 'الإسبانية (المكسيك)'],
            ['code' => 'en-gb', 'native_name' => 'English (UK)', 'direction' => 'ltr', 'name_en' => 'English (UK)', 'name_ar' => 'الإنجليزية (المملكة المتحدة)'],
            ['code' => 'en-us', 'native_name' => 'English (US)', 'direction' => 'ltr', 'name_en' => 'English (US)', 'name_ar' => 'الإنجليزية (الولايات المتحدة)'],
            ['code' => 'ckb', 'native_name' => 'کوردیی ناوەندی', 'direction' => 'rtl', 'name_en' => 'Central Kurdish (Sorani)', 'name_ar' => 'الكردية السورانية'],
            ['code' => 'kmr', 'native_name' => 'Kurmancî', 'direction' => 'ltr', 'name_en' => 'Northern Kurdish (Kurmanji)', 'name_ar' => 'الكردية الكرمانجية'],
            ['code' => 'bal', 'native_name' => 'بلوچی', 'direction' => 'rtl', 'name_en' => 'Balochi', 'name_ar' => 'البلوشية'],
            ['code' => 'skr', 'native_name' => 'سرائیکی', 'direction' => 'rtl', 'name_en' => 'Saraiki', 'name_ar' => 'السرائيكية'],
            ['code' => 'kok', 'native_name' => 'कोंकणी', 'direction' => 'ltr', 'name_en' => 'Konkani', 'name_ar' => 'الكونكانية'],
            ['code' => 'mai', 'native_name' => 'मैथिली', 'direction' => 'ltr', 'name_en' => 'Maithili', 'name_ar' => 'الميثيلية'],
            ['code' => 'sat', 'native_name' => 'ᱥᱟᱱᱛᱟᱲᱤ', 'direction' => 'ltr', 'name_en' => 'Santali', 'name_ar' => 'السانتالية'],
            ['code' => 'mni', 'native_name' => 'মৈতৈলোন্', 'direction' => 'ltr', 'name_en' => 'Manipuri', 'name_ar' => 'المانيبورية'],
            ['code' => 'tcy', 'native_name' => 'ತುಳು', 'direction' => 'ltr', 'name_en' => 'Tulu', 'name_ar' => 'التولو'],
            ['code' => 'ace', 'native_name' => 'Bahsa Acèh', 'direction' => 'ltr', 'name_en' => 'Acehnese', 'name_ar' => 'الأتشيهية'],
            ['code' => 'bug', 'native_name' => 'Basa Ugi', 'direction' => 'ltr', 'name_en' => 'Buginese', 'name_ar' => 'البوغيسية'],
            ['code' => 'min', 'native_name' => 'Baso Minangkabau', 'direction' => 'ltr', 'name_en' => 'Minangkabau', 'name_ar' => 'المينانغكابو'],
            ['code' => 'ber', 'native_name' => 'Tamaziɣt', 'direction' => 'ltr', 'name_en' => 'Berber', 'name_ar' => 'الأمازيغية'],
            ['code' => 'kab', 'native_name' => 'Taqbaylit', 'direction' => 'ltr', 'name_en' => 'Kabyle', 'name_ar' => 'القبائلية'],
            ['code' => 'shi', 'native_name' => 'ⵜⴰⵛⵍⵃⵉⵜ', 'direction' => 'ltr', 'name_en' => 'Tachelhit', 'name_ar' => 'التاشلحيت'],
            ['code' => 'ary', 'native_name' => 'الدارجة المغربية', 'direction' => 'rtl', 'name_en' => 'Moroccan Arabic', 'name_ar' => 'العربية المغربية'],
            ['code' => 'arz', 'native_name' => 'المصرية', 'direction' => 'rtl', 'name_en' => 'Egyptian Arabic', 'name_ar' => 'العربية المصرية'],
            ['code' => 'apc', 'native_name' => 'الشامية', 'direction' => 'rtl', 'name_en' => 'Levantine Arabic', 'name_ar' => 'العربية الشامية'],
            ['code' => 'afb', 'native_name' => 'الخليجية', 'direction' => 'rtl', 'name_en' => 'Gulf Arabic', 'name_ar' => 'العربية الخليجية'],
        ];
    }

    public function run(): void
    {
        foreach ($this->languages() as $index => $data) {
            $language = Language::updateOrCreate(
                ['code' => $data['code']],
                [
                    'native_name' => $data['native_name'],
                    'direction' => $data['direction'],
                    'sort_order' => $index + 1,
                    'is_active' => true,
                    'is_crud_locale' => in_array($data['code'], ['en', 'ar'], true),
                ]
            );

            syncModelTranslations($language, [
                'en' => ['name' => $data['name_en']],
                'ar' => ['name' => $data['name_ar']],
            ]);
        }

        Language::forgetCrudLocaleCache();
    }
}
